### ISSUE TITLE
Cannot read property 'removeChild' of null 

### ISSUE THREAD

**Issue by khanhvu161188** [sachinchoolur/lg-thumbnail.js#4]
If I setup like this 
```
lightGallery(document.getElementById('lightgallery'), { 
      thumbnail: true
    });
```

and then call the method by hitting a button ( for reloading the data) :
```
window.lgData[document.getElementById('lightgallery').getAttribute('lg-uid')].destroy(false);
```

It will throw the error `Cannot read property 'removeChild' of null `

**Comment by dweber019** [comment]
@khanhvu161188 in my case this worked
`window.lgData[document.getElementById('lightgallery').getAttribute('lg-uid')].destroy(true);`

passing `true` to `destroy` method.

**Comment by sachinchoolur** [comment]
The issue has been fixed. Please use the latest version of lightgallery.js and lg-thumbnail.js

**Comment by erkage** [comment]
What if i have this issue with the latest versions?
My code where it occurs:
```
let lg = document.getElementById("lightGallery");
lg.addEventListener('onSlideClick', function () {
	window.lgData[lg.getAttribute('lg-uid')].destroy();
}, false);

lg.addEventListener('onCloseAfter', function () {
	if (lg.getAttribute('lg-uid'))
		window.lgData[lg.getAttribute('lg-uid')].destroy(true);
}, false);

window.lightGallery(lg, {
	index: imageIndex,
	hideBarsDelay: 20000,
	preload: 3,
	speed: 0,
	//enableDrag: false,
	dynamic: true,
	dynamicEl: this.imgs(),
	thumbnail:true,
});
```
And getting the following error:
```
Uncaught TypeError: Cannot read property 'removeChild' of null
    at Thumbnail.destroy (lg-thumbnail.js?5fcc:478)
    at Plugin.destroy (lightgallery.js?4689:1364)
    at HTMLDivElement.eval (ModelCard.vue?f04d:135)
    at Object.trigger (lg-utils.js?c7c8:96)
    at eval (lightgallery.js?4689:1238)
```

**Comment by h3** [comment]
I confirm this issue is still occurring with latest version (1.2.0).

Here's the affected browsers I got:

- Chrome Mobile **86.0.4240** / **88.0.4324**
- Chrome **87.0.4280** / **88.0.4324**
- Edge **88.0.705**
- Opera Mobile **61.2.3076**
- Samsung Internet **13.2**
